blueprint:
  name: Ball Python Lighting Schedule
  description: >
    Controls UVB light and WLED presets based on sunrise, sunset, and fixed time.
    - Turns UVB ON + WLED to Morning preset 1 hour after sunrise
    - Turns UVB OFF + WLED to Night preset 30 min after sunset
    - Turns all WLED OFF at 22:00
  domain: automation
  input:
    uvb_light:
      name: UVB Light Entity
      selector:
        entity:
          domain: light

    wled_light:
      name: WLED Light Entity
      selector:
        entity:
          domain: light

    wled_preset_select:
      name: WLED Preset Selector (select entity)
      selector:
        entity:
          domain: select

    morning_preset:
      name: Morning Preset Name
      selector:
        text:

    night_preset:
      name: Night Preset Name
      selector:
        text:

trigger:
  - platform: sun
    event: sunrise
    offset: "01:00:00"
    id: sunrise_plus_1h

  - platform: sun
    event: sunset
    offset: "00:30:00"
    id: sunset_plus_30m

  - platform: time
    at: "22:00:00"
    id: night_shutdown

action:
  - choose:

      # 🌅 1 hour after sunrise
      - conditions:
          - condition: trigger
            id: sunrise_plus_1h
        sequence:
          - service: light.turn_on
            target:
              entity_id: !input uvb_light
          - service: select.select_option
            target:
              entity_id: !input wled_preset_select
            data:
              option: !input morning_preset
          - service: light.turn_on
            target:
              entity_id: !input wled_light

      # 🌇 30 min after sunset
      - conditions:
          - condition: trigger
            id: sunset_plus_30m
        sequence:
          - service: light.turn_off
            target:
              entity_id: !input uvb_light
          - service: select.select_option
            target:
              entity_id: !input wled_preset_select
            data:
              option: !input night_preset
          - service: light.turn_on
            target:
              entity_id: !input wled_light

      # 🌌 Full lights off at 22:00
      - conditions:
          - condition: trigger
            id: night_shutdown
        sequence:
          - service: light.turn_off
            target:
              entity_id: !input wled_light
