blueprint:
  name: Ball Python Temp Control
  description: >
    Regulates basking and CTE heat sources based on day/night mode and warm-side temperature.
    Includes failsafe shutdown at 35°C.
  domain: automation
  input:
    warm_side_sensor:
      name: Warm Side Temperature Sensor
      selector:
        entity:
          domain: sensor
          device_class: temperature

    basking_switch:
      name: Basking Light Switch
      selector:
        entity:
          domain: light

    cte_switch:
      name: Ceramic Tile Emitter (CTE) Switch
      selector:
        entity:
          domain: switch

    day_mode_boolean:
      name: Day Mode Boolean
      selector:
        entity:
          domain: input_boolean

    day_target_temp:
      name: Day Target Temperature (°C)
      selector:
        number:
          min: 20
          max: 40
          step: 0.5
          unit_of_measurement: °C

    night_target_temp:
      name: Night Target Temperature (°C)
      selector:
        number:
          min: 15
          max: 30
          step: 0.5
          unit_of_measurement: °C

    buffer:
      name: Temperature Buffer (±°C)
      default: 1
      selector:
        number:
          min: 0.5
          max: 3
          step: 0.5
          unit_of_measurement: °C

trigger:
  - platform: state
    entity_id: !input warm_side_sensor
    for:
      seconds: 30

condition: []

action:
  - variables:
      warm_sensor: !input warm_side_sensor
      day_mode: !input day_mode_boolean
      current_temp: "{{ states(warm_sensor) | float }}"
      is_day: "{{ is_state(day_mode, 'on') }}"
      target_temp: >
        {% if is_state(day_mode, 'on') %}
          {{ float(!input day_target_temp) }}
        {% else %}
          {{ float(!input night_target_temp) }}
        {% endif %}
      buffer: !input buffer

  - choose:

      - conditions:
          - condition: template
            value_template: "{{ current_temp > 35 }}"
        sequence:
          - service: light.turn_off
            target:
              entity_id: !input basking_switch
          - service: switch.turn_off
            target:
              entity_id: !input cte_switch
          - stop: true

      - conditions:
          - condition: template
            value_template: "{{ current_temp < (target_temp - buffer | float) }}"
        sequence:
          - service: switch.turn_on
            target:
              entity_id: !input cte_switch
          - condition: template
            value_template: "{{ is_day }}"
          - service: light.turn_on
            target:
              entity_id: !input basking_switch

      - conditions:
          - condition: template
            value_template: "{{ current_temp > (target_temp + buffer | float) }}"
        sequence:
          - service: switch.turn_off
            target:
              entity_id: !input cte_switch
          - condition: template
            value_template: "{{ is_day }}"
          - service: light.turn_on
            target:
              entity_id: !input basking_switch

      - conditions:
          - condition: template
            value_template: >
              {{ (current_temp >= (target_temp - buffer | float)) and
                 (current_temp <= (target_temp + buffer | float)) }}
        sequence:
          - service: switch.turn_off
            target:
              entity_id: !input cte_switch
          - choose:
              - conditions:
                  - condition: template
                    value_template: "{{ is_day }}"
                sequence:
                  - service: light.turn_on
                    target:
                      entity_id: !input basking_switch
              - conditions:
                  - condition: template
                    value_template: "{{ not is_day }}"
                sequence:
                  - service: light.turn_off
                    target:
                      entity_id: !input basking_switch
