blueprint:
  name: Ball Python Temp Control
  description: >
    Regulates basking and CTE heat sources based on day/night mode and warm-side temperature.
    Includes failsafe shutdown at 35°C.
  domain: automation
  input:
    warm_side_sensor:
      name: Warm Side Temperature Sensor
      selector:
        entity:
          domain: sensor
          device_class: temperature

    basking_switch:
      name: Basking Light Switch
      selector:
        entity:
          domain: light

    cte_switch:
      name: Ceramic Tile Emitter (CTE) Switch
      selector:
        entity:
          domain: switch

    day_mode_boolean:
      name: Day Mode Boolean
      selector:
        entity:
          domain: input_boolean

    day_target_temp:
      name: Day Target Temperature (°C)
      selector:
        number:
          min: 20
          max: 40
          step: 0.5
          unit_of_measurement: °C

    night_target_temp:
      name: Night Target Temperature (°C)
      selector:
        number:
          min: 15
          max: 30
          step: 0.5
          unit_of_measurement: °C

    buffer:
      name: Temperature Buffer (±°C)
      default: 1
      selector:
        number:
          min: 0.5
          max: 3
          step: 0.5
          unit_of_measurement: °C

trigger:
  - platform: state
    entity_id: !input warm_side_sensor
    for:
      seconds: 30

condition: []

action:
  - choose:

      # FAILSAFE
      - conditions:
          - condition: template
            value_template: >
              {{ states('!input warm_side_sensor') | float > 35 }}
        sequence:
          - service: light.turn_off
            target:
              entity_id: !input basking_switch
          - service: switch.turn_off
            target:
              entity_id: !input cte_switch
          - stop: true

      # TOO COLD
      - conditions:
          - condition: template
            value_template: >
              {% set temp = states('!input warm_side_sensor') | float %}
              {% set target = (is_state('!input day_mode_boolean', 'on') | iif(!input day_target_temp, !input night_target_temp)) | float %}
              {% set buffer = !input buffer | float %}
              {{ temp < (target - buffer) }}
        sequence:
          - service: switch.turn_on
            target:
              entity_id: !input cte_switch
          - condition: template
            value_template: "{{ is_state('!input day_mode_boolean', 'on') }}"
          - service: light.turn_on
            target:
              entity_id: !input basking_switch

      # TOO HOT
      - conditions:
          - condition: template
            value_template: >
              {% set temp = states('!input warm_side_sensor') | float %}
              {% set target = (is_state('!input day_mode_boolean', 'on') | iif(!input day_target_temp, !input night_target_temp)) | float %}
              {% set buffer = !input buffer | float %}
              {{ temp > (target + buffer) }}
        sequence:
          - service: switch.turn_off
            target:
              entity_id: !input cte_switch
          - condition: template
            value_template: "{{ is_state('!input day_mode_boolean', 'on') }}"
          - service: light.turn_on
            target:
              entity_id: !input basking_switch

      # IN RANGE
      - conditions:
          - condition: template
            value_template: >
              {% set temp = states('!input warm_side_sensor') | float %}
              {% set target = (is_state('!input day_mode_boolean', 'on') | iif(!input day_target_temp, !input night_target_temp)) | float %}
              {% set buffer = !input buffer | float %}
              {{ temp >= (target - buffer) and temp <= (target + buffer) }}
        sequence:
          - service: switch.turn_off
            target:
              entity_id: !input cte_switch
          - choose:
              - conditions:
                  - condition: template
                    value_template: "{{ is_state('!input day_mode_boolean', 'on') }}"
                sequence:
                  - service: light.turn_on
                    target:
                      entity_id: !input basking_switch
              - conditions:
                  - condition: template
                    value_template: "{{ is_state('!input day_mode_boolean', 'off') }}"
                sequence:
                  - service: light.turn_off
                    target:
                      entity_id: !input basking_switch
