blueprint:
  name: Day/Night Mode Toggle (Sun-based)
  description: >
    Automatically sets day or night mode by toggling a day_mode input_boolean
    based on sunrise and sunset.
  domain: automation
  input:
    day_mode_boolean:
      name: Day Mode Boolean
      description: The input_boolean used to control day/night mode.
      selector:
        entity:
          domain: input_boolean

trigger:
  - platform: sun
    event: sunrise
    id: sunrise

  - platform: sun
    event: sunset
    id: sunset

action:
  - choose:
      - conditions:
          - condition: trigger
            id: sunrise
        sequence:
          - service: input_boolean.turn_on
            target:
              entity_id: !input day_mode_boolean

      - conditions:
          - condition: trigger
            id: sunset
        sequence:
          - service: input_boolean.turn_off
            target:
              entity_id: !input day_mode_boolean
